# Copyright (C) 2017-2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/oppo/r9s/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/oppo/r9s/proprietary/recovery/root/sbin/qseecomd:system/recovery/root/sbin/qseecomd \
    vendor/oppo/r9s/proprietary/recovery/root/vendor/lib64/hw/keystore.msm8953.so:system/recovery/root/vendor/lib64/hw/keystore.msm8953.so \
    vendor/oppo/r9s/proprietary/recovery/root/vendor/lib64/libQSEEComAPI.so:system/recovery/root/vendor/lib64/libQSEEComAPI.so \
    vendor/oppo/r9s/proprietary/recovery/root/vendor/lib64/libdiag.so:system/recovery/root/vendor/lib64/libdiag.so \
    vendor/oppo/r9s/proprietary/recovery/root/vendor/lib64/libdrmfs.so:system/recovery/root/vendor/lib64/libdrmfs.so \
    vendor/oppo/r9s/proprietary/recovery/root/vendor/lib64/libdrmtime.so:system/recovery/root/vendor/lib64/libdrmtime.so \
    vendor/oppo/r9s/proprietary/recovery/root/vendor/lib64/librpmb.so:system/recovery/root/vendor/lib64/librpmb.so \
    vendor/oppo/r9s/proprietary/recovery/root/vendor/lib64/libssd.so:system/recovery/root/vendor/lib64/libssd.so
